name: Build and Test

# Controls when the workflow will run.
on:
  # Triggers the workflow on push events but only for the "main" branch.
  push:
    branches: [ "master" ]
  # Triggers the workflow on pull request events targeted at the "main" branch.
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This job is named "build-and-test".
  build-and-test:
    # The type of runner that the job will run on. "ubuntu-latest" is a standard choice.
    runs-on: ubuntu-latest

    # This creates a build matrix to test against multiple PHP versions in parallel.
    # This is key for ensuring your library has broad compatibility.
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # 1. Get the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up the specific PHP version for this job run from the matrix.
      # This uses a popular and highly-rated action for PHP environments.
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl # Add common extensions if your code needs them.
          tools: composer:v2
          coverage: none # Set to xdebug or pcov if you want code coverage reports.

      # 3. Cache Composer dependencies to speed up subsequent builds.
      # The cache is invalidated only when your composer.lock file changes.
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # 4. Install project dependencies using Composer.
      # The flags are optimized for CI environments (non-interactive, faster).
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      # 5. Run PHP Code Sniffer to check for coding standards violations.
      - name: Run PHPCS (Code Style)
        run: composer cs

      # 6. Run PHPStan for static analysis to find potential bugs.
      - name: Run PHPStan (Static Analysis)
        run: composer stan

      # 7. Run the unit tests with PHPUnit. The primary goal of your request.
      - name: Run PHPUnit (Unit Tests)
        run: composer test
